name: Push the Docker image to AWS ECR Repo
on:
  push:
    branches:
      - dev

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch the last two commits to access the latest and previous commit hashes

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get latest two commit hashes
        id: commits
        run: |
          echo "LATEST_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "PREVIOUS_COMMIT=$(git rev-parse --short HEAD~1)" >> $GITHUB_ENV

      - name: Build, tag, and push backend images to Amazon ECR
        working-directory: ./backend
        run: |
          LATEST_COMMIT=${{ env.LATEST_COMMIT }}
          PREVIOUS_COMMIT=${{ env.PREVIOUS_COMMIT }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=docker-practice

          # Build and push images for latest and previous commits with --no-cache to ensure unique images
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:backend-$LATEST_COMMIT .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:backend-$LATEST_COMMIT
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:backend-$PREVIOUS_COMMIT .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:backend-$PREVIOUS_COMMIT

      - name: Build, tag, and push frontend images to Amazon ECR
        working-directory: ./frontend
        run: |
          LATEST_COMMIT=${{ env.LATEST_COMMIT }}
          PREVIOUS_COMMIT=${{ env.PREVIOUS_COMMIT }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=docker-practice

          # Build and push images for latest and previous commits with --no-cache to ensure unique images
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$LATEST_COMMIT .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$LATEST_COMMIT
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$PREVIOUS_COMMIT .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$PREVIOUS_COMMIT
