name: Push the Docker image to AWS ECR Repo

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which working directory to work on
        options: 
        - backend
        - frontend
        required: true 
        
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get latest commit hash
        id: commits
        run: |
          echo "LATEST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build, tag, and push backend or frontend images to Amazon ECR using inputs
        working-directory: ./${{ github.event.inputs.name }}
        run: |
          LATEST_COMMIT=${{ github.event.inputs.name }}-${{ env.LATEST_COMMIT }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=docker-practice  # Repository name in ECR

          # Build and push image with unique tag
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST_COMMIT .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST_COMMIT
